import type { Metadata } from 'next';
import './globals.css';
import { AppProviders } from '@/providers/AppProvider';
// Supports weights 100-900
import '@fontsource-variable/dm-sans/opsz-italic.css';
import LayoutContainer from '@/shared/components/Layout/LayoutContainer';
import { InitColorSchemeScript } from '@mui/material';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`} suppressHydrationWarning>
      <body className="min-h-full flex flex-col">
        <InitColorSchemeScript attribute="class" />
        <AppProviders>
          <LayoutContainer>{children}</LayoutContainer>
        </AppProviders>
      </body>
    </html>
  );
}
