import type { Metadata } from 'next';
import './globals.css';
import { AppProviders } from '@/providers/AppProvider';
// Supports weights 100-900
import '@fontsource-variable/dm-sans/opsz-italic.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
